### PR TITLE
Add flower pots

### PR DESCRIPTION
**Pull request by sae220**

### CODE REVIEW

**Comment by Pinary-Pi** [comment]
This is a super cool idea! I will be testing the code out and if it works, I'll merge it. I'll also probably change the textures before I release it to CurseForge.

**Comment by Pinary-Pi** [comment]
In 1.16, most things work pretty well. Ferns are gray in the pots, so that needs to be fixed. As well as their aren't crafting recipes for combing a pot with a dye to get a colored pot. I'm not quite sure why the ferns are gray, but I'll look into it. The crafting recipes should be an easy fix. So far, so good!

**Comment by sae220** [comment]
(Sorry for my poor English)
Thanks for your testing.
I suppose potted ferns are gray because I didn't code about BlockColors.
I found vanilla fern texture is not green but gray.
Like grass block or water block, the texture varies in the color according to biomes.
I'll fix it.

**Comment by sae220** [comment]
About dying recipes, which one is better, 1:1 like wool or 1:8 like terracotta or glass?

**Comment by Pinary-Pi** [comment]
> About dying recipes, which one is better, 1:1 like wool or 1:8 like terracotta or glass?

I think that 1:1 would make more sense in this instance.

**Comment by sae220** [comment]
Which ingredient of dyeing recipe is better, any color one like shulker box or only vanilla one like wool?

**Comment by Pinary-Pi** [comment]
> Which ingredient of dyeing recipe is better, any color one like shulker box or only vanilla one like wool?

I'm a little bit confused as to what you mean. However, for the recipe I would make it be one pot and one colored dye placed anywhere crafts a colored pot related to the dye. If you want, I could maybe make the recipes, though it would probably be done on Saturday as I got school and stuff.

**Comment by sae220** [comment]
Sorry, I misunderstood much about recipes. Please ignore what I just said.
I should create json files like the following, right?
```json:white_flower_pot_from_vanilla_flower_pot.json
{
  "type": "minecraft:crafting_shapeless",
  "ingredients": [
    {
      "item": "minecraft:flower_pot"
    },
    {
      "tag": "forge:dyes/white"
    }
  ],
  "result": {
    "item": "coloredbricks:white_flower_pot"
  }
}
```

**Comment by Pinary-Pi** [comment]
> Sorry, I misunderstood much about recipes. Please ignore what I just said.
> I should create json files like the following, right?
> ```json:white_flower_pot_from_vanilla_flower_pot.json
> {
>   "type": "minecraft:crafting_shapeless",
>   "ingredients": [
>     {
>       "item": "minecraft:flower_pot"
>     },
>     {
>       "tag": "forge:dyes/white"
>     }
>   ],
>   "result": {
>     "item": "coloredbricks:white_flower_pot"
>   }
> }
> ```

Yes, that should be good 👍 Thanks for the work you're putting into this.

**Comment by sae220** [comment]
I added the recipes.
Thank you so much for your help.

**Comment by Pinary-Pi** [comment]
> I added the recipes. Thank you so much for your help.

Awesome! I tested everything in 1.16 out. I'll just be testing it out in the other versions later today.

**Comment by Pinary-Pi** [comment]
Okay, so I was trying to test everything out, but for some reason the runClient command isn't working for me. After various testing I've not figured out why, but it isn't related to any code (afaik) in the Colored Bricks Mod folders. However, the build command works and the produced .jar file for 1.17 had no issues running in Minecraft. There were also no bugs that I found regarding the pots! So 1.17 is good 👍

**Comment by Pinary-Pi** [comment]
> Okay, so I was trying to test everything out, but for some reason the runClient command isn't working for me. After various testing I've not figured out why, but it isn't related to any code (afaik) in the Colored Bricks Mod folders. However, the build command works and the produced .jar file for 1.17 had no issues running in Minecraft. There were also no bugs that I found regarding the pots! So 1.17 is good 👍

This was all for 1.17 btw. These complications prohibited me from testing 1.18 and 1.19.

**Comment by sae220** [comment]
So you mean the runClinent command for 1.17-1.19 isn't working but you can build .jar file only for 1.17?

**Comment by Pinary-Pi** [comment]
> So you mean the runClinent command for 1.17-1.19 isn't working but you can build .jar file only for 1.17?

At that point, I had only tried running the tasks with 1.17. However today, I tried it with 1.18 and 1.19 and found the same thing. I can't run the runClient task, but the build task works and the produced .jar file also works in Minecraft as well. So, 1.18 and 1.19 should be good. I think there's something wrong on my end. I'm not sure what, but I'll be looking into it.

**Pull request merged**
